# Generated by Django 5.2.7 on 2025-12-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_productvariant_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
