# Generated by Django 5.2.7 on 2025-12-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productvariant_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="price",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
