# Generated by Django 5.2.7 on 2025-12-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_productvariant_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_image"),
        ),
    ]
