# Generated by Django 5.2.7 on 2026-02-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_base_price_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="base_image",
            field=models.ImageField(default=None, upload_to="product_image"),
        ),
    ]
